### ISSUE TITLE
Usability for self-typing code

### ISSUE THREAD

**Issue by zmontgo** [benjaminbhollon/see-with-eyes-closed#11]
Make a button to automatically skip the typing animation. Make it skip it by default if on mobile, and show the final product with a button to switch to the code. Easier to see on the smaller screen.

**Comment by benjaminbhollon** [comment]
Where do we place the button?

**Comment by zmontgo** [comment]
Preferably to the top right.

**Comment by benjaminbhollon** [comment]
To clarify--you're meaning the live-coding animation of the avocado, correct?
