### ISSUE TITLE
Use database to find similar articles

### ISSUE THREAD

**Issue by zmontgo** [benjaminbhollon/see-with-eyes-closed#13]
Looping over every article is hugely inefficient for the code, and with more than a couple hundred is nearly unusable. Use the database to select all by matching tag and sort by number of matching.

**Comment by benjaminbhollon** [comment]
This is yours if you want it

**Comment by benjaminbhollon** [comment]
@zmontgo Aggregation should work great for this. Try making a crud function for it and then use this article as a guide for the specific aggregation that will solve this problem:

https://stackoverflow.com/questions/27326748/mongodb-find-documents-that-match-the-most-tags

Let me know if you need help.

**Comment by benjaminbhollon** [comment]
Solved! :)
