### ISSUE TITLE
Use ESLint

### ISSUE THREAD

**Issue by zmontgo** [benjaminbhollon/see-with-eyes-closed#4]
Use ESLint to enforce syntax style and catch errors. Will be a helpful part of the review process before pulling into the main branch. Use GitHub Actions to automate this and prevent people from pulling until the linter errors are fixed. Also require at least one review, in case you ever have more than just you and I working on this project, it can be helpful to ensure that someone has manually gone through and looked at the code to make sure it all works well.
Just putting this as an issue because I have no idea how to set it up myself.

**Comment by zmontgo** [comment]
Good style guide for ESLint: https://github.com/airbnb/javascript
Helps keep lines short, etc. I generally dislike including strings inside classes at all, preferring to put them inside config files. Probably going to make this a future change with my current PR.

**Comment by benjaminbhollon** [comment]
I've set it up to require a review. I'll take a look at ESLint.
