### ISSUE TITLE
Extend README

### ISSUE THREAD

**Issue by zmontgo** [benjaminbhollon/see-with-eyes-closed#5]
Update the README to include the following information:
1. A paragraph or so about the blog itself.
2. Add a link to [CONTRIBUTING.md](https://gist.github.com/PurpleBooth/b24679402957c63ec426) and LICENSE
3. Add an explicit invitation to contribute in any way people think could be helpful. This isn’t just a place to store code! Fans should be able to help you develop the website... I suggest also putting a link to the repo in the footer of the website itself.
4. How to set up a development environment.

**Comment by benjaminbhollon** [comment]
Okay, ig now might be a good time to do this...

**Comment by benjaminbhollon** [comment]
I iz done! 🤩
