### ISSUE TITLE
Use ESLint to check errors

### ISSUE THREAD

**Issue by zmontgo** [benjaminbhollon/see-with-eyes-closed#7]
I ran ESLint using some settings and received over 4,000 errors. Make sure your code is well-formatted!

**Comment by zmontgo** [comment]
This may be a group effort. I'll do the first good chunk, then you can look at my PR I'll make and help finish up. By the end we should have nice and readable code for future development.

**Comment by benjaminbhollon** [comment]
4,000 errors sounds wrong; I don't think I even have that many lines of code.
