### ISSUE TITLE
Put app function in separate file

### ISSUE THREAD

**Issue by zmontgo** [benjaminbhollon/see-with-eyes-closed#9]
Extrapolate the `app.get` and `app.post` functions out into a separate file (or two, for both get and post). Import and run them in `app.js`.

**Comment by benjaminbhollon** [comment]
Instead of filtering by GET and POST requests, I'm going to separate by function. Admin requests in one place, website pages on another, form handling ones in another, etc.

**Comment by benjaminbhollon** [comment]
Done with the admin functions; I'll do it with others if necessary.
